### ISSUE TITLE
Where is the example?

### ISSUE THREAD

**Issue by joseluisgs** [UstadMobile/door#6]
Please, I try to access to: https://github.com/UstadMobile/door-example
But 404 not found
Could you help me?

**Comment by mikedawson** [comment]
The link seems to work fine:

![Screenshot from 2022-11-27 16-06-43](https://user-images.githubusercontent.com/4280622/204134412-1b34c5f1-c570-49e0-b5c9-153bbb905989.png)

**Comment by joseluisgs** [comment]
I have 404. Is It a public repo?
I see private at the image

**Comment by mikedawson** [comment]
Oops! @joseluisgs  - I have no idea why that repo was private. I have made it public. You should be able to access it. Sorry.

**Comment by joseluisgs** [comment]
Thank you 👍👍👍
